source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'

install! 'cocoapods', :disable_input_output_paths => true
platform :ios, '10.0'

#use_frameworks!
def common
  pod 'RangersAppLog',:path => '../'
#  pod 'RangersAppLog','4.5.0'
end
target 'OCDemo' do
  common
end

target 'SwiftDemo' do
  common
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
  
end
